MobilFav/urls.py
from django.urls import path

from .views import *

app_name = 'MobilFav'

urlpatterns = [
    path('', wish, name='wish'),
    path('add/<str:carname>/', wish_add, name='wish_add'),
    path('item_clear/<str:carname>/', item_clear, name='wish_clear'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('shop/', include('shop.urls')),
    path('article/', include('artikel.urls')),
    path('wishlist/', include('MobilFav.urls'))
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MobilFav/models.py
from __future__ import unicode_literals

from django.db import models

from shop.models import Mobil


class MobilFavorit(models.Model):
    mobil = models.ForeignKey(Mobil, on_delete=models.SET_NULL, null=True)
    date_added = models.DateTimeField(auto_now=True)

MobilFav/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from .models import MobilFavorit
from cart.cart import Cart
from django.contrib.auth.decorators import login_required
from shop.models import Mobil

# @login_required(login_url="/otentikasi/login/")
def wish_add(request, carname):
    cart = Cart(request)
    mobil = Mobil.objects.get(name=carname)
    if mobil.image is None:
        mobil.image = "/static/1.jpg"
    cart.add(product=mobil)
    try:
        mobil1 = MobilFavorit.objects.get(mobil=mobil)
    except MobilFavorit.DoesNotExist:
        mobil_favorit = MobilFavorit.objects.create(mobil=mobil)
        mobil_favorit.save()
    return redirect("/shop/details/"+carname)


# @login_required(login_url="/otentikasi/login/")
def item_clear(request, carname):
    cart = Cart(request)
    product = Mobil.objects.get(name=carname)
    cart.remove(product)
    mobil_favorit = MobilFavorit.objects.get(mobil=product)
    mobil_favorit.delete()
    return redirect("MobilFav:wish")

# @login_required(login_url="/otentikasi/login/")
def wish(request):
    mobil_favorit = MobilFavorit.objects.all()
    if len(mobil_favorit) == 0:
        cart = Cart(request)
        cart.clear()
    return render(request, 'wishlist.html')
    

MobilFav/templates/wishlist.html
{% extends 'nav.html' %}
{% block content %}
<div class="jumbotron jumbotron-fluid bg-light">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            {% for key,value in request.session.cart.items %}
            <div class="container" id="barang">
                <div class="row">
                    <div class="col-3">
                        <img src="{{ value.image.url }}" width="150px">
                    </div>
                    <div class="col-7">
                        <h2 class="barang1-typo">
                            <a href="/shop/details/{{value.name}}">{{ value.name }}</a>
                        </h2>
                        <h3>Harga: {{ value.price }}</h3>
                        
                    </div>
                    <div class="col-2">
                        <h1>
                            <a href="{% url 'MobilFav:wish_clear' value.name %}"><i class="fa fa-trash" aria-hidden="true"></i>
                            </a>
                        </h1>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
            
    </div>
</div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>


{% endblock %}