MobilFav/urls.py
from django.urls import path

from .views import *

app_name = 'MobilFav'

urlpatterns = [
    path('', wish, name='wish'),
    path('add/<str:carname>/', wish_add, name='wish_add'),
    path('item_clear/<str:carname>/', item_clear, name='wish_clear'),
]

shop/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', shop, name='shop'),
    path('details/<str:carname>', details, name='details'),
    path('daftar/', daftar, name='daftar'),
    path('rent_form/<str:carname>', rent_form, name="rent_form"),
    path('review_form/<str:carname>', review_form, name="review_form"),
    path('api/get_cars_by_query/<str:query>', get_cars_by_query, name="get_cars_by_query"),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('shop/', include('shop.urls')),
    path('article/', include('artikel.urls')),
    path('wishlist/', include('MobilFav.urls'))
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.db.models.fields.files import ImageField

class Mobil(models.Model):
    name = models.CharField(max_length=255, default="", unique=True)
    username = models.CharField(max_length=255, default="")
    desc = models.TextField(max_length=1028, default="")
    tahun = models.IntegerField(default=0)
    kota = models.CharField(max_length=255, default="")
    price = models.CharField(max_length=255, default="")
    image = models.FileField(null=True,blank=True, upload_to='media/')
    # tipe = models.ForeignKey(Kategori, )

    def __str__(self):
        return self.name

class Ulasan(models.Model):
    username = models.CharField(max_length=255, default="")
    mobil = models.ForeignKey(Mobil, on_delete=models.CASCADE)
    pesan = models.TextField(max_length=2056, default="")
    date = models.DateField(auto_now_add=True)
    rating = models.FloatField()

    def __str__(self):
        return self.username

class Transaksi(models.Model):
    penyewa = models.CharField(max_length=255, blank=False)
    mobilSewa = models.ForeignKey(Mobil, on_delete=models.CASCADE)
    lamaSewa = models.IntegerField()
    tanggal = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.penyewa

shop/forms.py
from django import forms
from . import models


class TransaksiForm(forms.ModelForm):
    class Meta:
        model = models.Transaksi
        fields = [
            "penyewa",
            "lamaSewa",
            
        ]
        labels = {
            "penyewa": "Nama",
            "lamaSewa": "Lama Sewa (hari)"
        }
        

class UlasanForm(forms.ModelForm):
    class Meta:
        model = models.Ulasan
        fields = [
            "username",
            "pesan",
            "rating",
        ]
        labels = {
            "username": "Username",
            "pesan": "Pesan",
            "rating": "Rating"
        }
        

class MobilForm(forms.ModelForm):
    class Meta:
        model = models.Mobil
        fields = [
            "name",
            "username",
            "desc",
            "tahun",
            "kota",
            "price",
            "image",
        ]
        labels = {
            "name": "Nama Lengkap",
            "username": "Username",
            "desc": "Deskripsi Mobil",
            "tahun": "Tahun Keluaran Mobil",
            "kota": "Lokasi",
            "price": "Harga Sewa (hari)"
        }

shop/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from .models import *
from .forms import *
from .serializers import MobilSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response

# Create your views here.
def shop(request):
    cars = Mobil.objects.all()
    return render(request, 'shop.html', {'cars' : cars})


def details(request, carname):
    # mobil = Mobil.objects.all()
    target = Mobil.objects.get(name=carname)
    image = target.image
    review = Ulasan.objects.filter(mobil__name=carname)
    transaksi = Transaksi.objects.filter(mobilSewa__name=carname)
    return render(request, 'details.html', {'review': review, 'transaksi': transaksi, 'target': target, 'image':image})


def daftar(request):
    response = {
        'mobil_form': MobilForm(),
        'status':False
    }
    if request.method == 'POST':
        mobil_form = MobilForm(request.POST)
        if mobil_form.is_valid():
            data = mobil_form.cleaned_data
            if data.get('tahun') > 0:
                mobil_form.save()
                return render(request, 'daftar.html', {'mobil_form':MobilForm(), 'status': 'Sukses Didaftarkan'})
            else:
                return render(request, 'daftar.html', {'mobil_form':MobilForm(), 'status': 'Terjadi kesalahan'})
    return render(request, 'daftar.html', response)


def rent_form(request, carname):
    if (request.method=="POST"):
        form = TransaksiForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.mobilSewa = Mobil.objects.get(name=carname)
            post.tanggal = timezone.now()
            post.save()
            return redirect('shop')

    form = TransaksiForm()
    return render(request, 'rent_form.html', {'form': form})


def review_form(request, carname):
    if (request.method=="POST"):
        form = UlasanForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.mobil = Mobil.objects.get(name=carname)
            post.date = timezone.now()
            post.save()
            return redirect('shop')
    
    form = UlasanForm()
    return render(request, 'review_form.html', {'form': form})

def suggestion(request):
    return render(request, 'suggestion.html')

@api_view(['GET'])
def get_cars_by_query(request, query):
    cars = []
    if query.isnumeric():
        cars = Mobil.objects.filter(price__range = (0, int(query)))
    else:
        cars = Mobil.objects.filter(name__icontains = query)
    serializer = MobilSerializer(cars, many=True)
    return Response(serializer.data)

shop/templates/daftar.html
{% extends 'nav.html'%}
{% block content %}

<div class="jumbotron jumbotron-fluid bg-light">
    <div class="container">

        <form method="POST" action="">
            {% csrf_token %}
            {% for field in mobil_form.visible_fields %}
            
            <div class="row justify-content-center">
                <div class="col-sm-3">{{field.label_tag}}</div>
                <div class="col-sm-5">{{field}}</div>
            </div>
            
            {% endfor %}
            <div class="row justify-content-center">
                <input class="btn btn-primary my-5 mx-3" type="submit" value="Daftar">
            </div>
        </form>
        {% if status %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-sm-8">
                    {% if status == 'Sukses Didaftarkan' %}
                    <div class="alert alert-success" role="alert" style="width: 70%;" >
                        Sukses mendaftarkan mobil anda.
                    </div>
                    {% else %}
                    <div class="alert alert-danger" role="alert" style="width: 70%;">
                        Terjadi kesalahan input, silahkan coba lagi
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        {% endif %}
    </div>
</div>
{% endblock %}

shop/templates/details.html
{% extends 'nav.html' %}
{% block content %}
<!-- HEADER: IMAGE, NAME & PRICE, SELLER'S DESC -->
    <div class="detail_header mt-4">
        {% if image %}
        <img src='{{target.image.url}}' class="detail_image" alt="car image">
        {% endif %}

        <div class="right ml-3" style="width: 100%;">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title" style="text-transform: uppercase;">{{target.name}}</h3>
                    <h5 class="card-title">{{target.price}}</h5>
                </div>
            </div>

            <div class="card mt-3">
                <div class="card-body">
                    <h3 class="card-title">SELLER'S DETAILS</h3>
                    <div class="content_flex" style="justify-content: start;">
                        <div class="content mr-5">
                            <h5 class="card-text">Nama</h5>
                            <div class="card-text mb-2">{{target.username}}</div>
                        </div>
                        <div class="content">
                            <h5 class="card-text">Lokasi</h5>
                            <div class="card-text">{{target.kota}}</div>        
                        </div>
                    </div>                    
                </div>
            </div>
        </div>
    </div>



    <!-- ITEM'S DESC -->
    <div class="card mt-3">
        <div class="card-body">
            <h3 class="card-title">ITEM'S DESCRIPTION</h3>
            <div class="card-text">{{target.desc}}</div>
        </div>
    </div>



    <!-- REVIEW -->
    <div class="card mt-3">
        <div class="card-body">
            <h3 class="card-title">REVIEW</h3>
            {% for item in review %}
            <div class="card mb-2">
                <div class="card-body">
                    <h5 class="card-title">
                        {{item.username}}
                        <h6>{{item.date}} / {{item.rating}} stars</h6>
                    </h5>
                    <p class="card-text">{{item.pesan}}</p>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>



    <!-- TRANSACTIONS -->
    <div class="card mt-3">
        <div class="card-body">
            <h3 class="card-title">TRANSACTIONS</h3>
            <div class="content_flex" style="flex-wrap: wrap;">
                {% for transaksis in transaksi %}
                <div class="card mb-2" style="width: 30%;">
                    <div class="card-body">
                        <h5 class="card-title">{{transaksis.tanggal}}</h5>
                        <div class="content_flex">
                            <div class="content">
                                <h5 class="card-text">Penyewa</h5>
                                <div class="card-text mb-2">{{transaksis.penyewa}}</div>
                            </div>
                            <div class="content">
                                <h5 class="card-text">Lama Waktu Sewa</h5>
                                <div class="card-text">{{transaksis.lamaSewa}} hari</div>    
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>



    <!-- RENT BUTTON -->
    <form action="" method="POST">
        {% csrf_token %}
        <div class="button_flex">
            <button class="detail_button mt-3 mb-4" formaction="{% url 'rent_form' target.name %}">RENT</button>
            <button class="detail_button mt-3 mb-4" formaction="{% url 'review_form' target.name %}">REVIEW</button>
            <button class="detail_button mt-3 mb-4" formaction="{% url 'MobilFav:wish_add' target.name %}" onclick="myFunction()">❤️ ADD TO WISHLIST</button>   
        </div>
    </form>
    <script>
        function myFunction() {
          alert("Barang berhasil ditambahkan ke keranjang!");
        }
    </script>

{% endblock %}

shop/templates/rent_form.html
{% extends 'nav.html' %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form_wrap mt-4">
            <div class="form">
                {{form.as_p}}
            </div>
            <button type="submit" class="detail_button" style="height:fit-content">Submit</button>
        </div>
    </form>
{% endblock %}

shop/templates/review_form.html
{% extends 'nav.html' %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form_wrap mt-4">
            <div class="form">
                {{form.as_p}}
            </div>
            <button type="submit" class="detail_button" style="height:fit-content">Submit</button>
        </div>
    </form>
{% endblock %}

shop/templates/shop.html
{% extends 'nav.html' %}
{% load static %}
{% block content %}
<script>
    $(document).ready(function() {
        $('.search').keyup(function() {
            if ($('.search').val() != "") {
                $('.content').empty()
                $.ajax({
                    method: 'GET',
                    url: `${window.location.href}api/get_cars_by_query/${$('.search').val()}`,
                    success: resp => {
                        console.log(resp);
                        $.map(resp, function(car) {
                            let dd_temp = `
                                <div class="dropdown">
                                    <a class="dd_name">${car.name}</a>
                                    <p class="dd_harga">Rp. ${car.price},-</p>
                                </div>
                            `
                            $('.content').append(dd_temp);
                        })
                    }
                })
            } else {
                $('.content').empty()                    
            }
        })
    })
</script>

<div class="row row-cols-1 row-cols-md-4 mt-4 mb-4">
    {% for item in cars %}
    <div class="col mb-4">
        <div class="card h-100 shop_card">
            {% if item.image %}
            <div class="image_box">
                <img src='{{item.image.url}}' class="shop_image rounded" alt="car image">
            </div>
            {% endif %}
            <div class="card-body shop_caption">
                <h4 class="card-title" style="font-weight: bold;">{{item.price}}</h4>
                <p class="card-text">{{item.tahun}} {{item.name}}</p>
                <a href="{% url 'details' item.name %}" class="btn shop_button">Details</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="dd_container">
    <h1>Looking for suggestions?</h1>

    <input class="search" placeholder="search for suggestions" type="text">

    <div class="content"></div>    
</div>
{% endblock %}